from pyleri import Token
And = Token('&')
Comma = Token(',')
Divide = Token('/')
Dot = Token('.')
Equals = Token('=')
Lbrace = Token('{')
Lbracket = Token('(')
LsquareBracket = Token('[')
Minus = Token('-')
Multiply = Token('*')
Not = Token('~')
Or = Token('|')
Plus = Token('+')
Rbrace = Token('}')
Rbracket = Token(')')
RsquareBracket = Token(']')
