from pyleri import Token

Lbrace = Token('{')
Rbrace = Token('}')
LsquareBracket = Token('[')
RsquareBracket = Token(']')
Lbracket = Token('(')
Rbracket = Token(')')
Comma = Token(',')
Dot = Token('.')
Equals = Token('=')
Plus = Token('+')
Minus = Token('-')
Multiply = Token('*')
Divide = Token('/')
Not = Token('~')
And = Token('&')
Or = Token('|')
